name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.c5bee2d9-782a-43bd-a47f-45925c654bc1}}
          heroku_app_name: "adam-app-perez" #Must be unique in Heroku
          heroku_email: "adam.perez@edu.devinci.fr"
